#!/usr/bin/env bash

watchexec --clear=reset \
  --ignore "docs/screenshots/*.png" \
  './build && \
   git add . && \
   echo "changes in source code:" && \
   git --no-pager diff --cached && \
   echo "" && echo "new files:"  && \
   git status --porcelain \
'
